const responses = [
    "Absolutely, the cosmos just winked at you.",
    "Negative, the void shook its head.",
    "Maybe, but only under a neon moon.",
    "Yes, if you enjoy surprise confetti.",
    "No, the toaster union vetoed it.",
    "Ask later; the ghosts are on lunch break.",
    "The answer is yes, whispered by glitter.",
    "The answer is no, sealed in cold fog.",
    "It’s possible, though mildly cursed.",
    "Sure, but bring a flashlight and courage.",
    "Not today; the jellyfish overlords object.",
    "Signs point to yes, humming softly.",
    "Outlook gloomy as a haunted teacup.",
    "Prepare for a yes wrapped in sarcasm.",
    "Denied by a council of sleepy owls.",
    "Affirmative, accompanied by spectral applause.",
    "No; reality locked that door.",
    "Looks good, but wear silver socks.",
    "Don’t count on it, the mirror screamed.",
    "Yes, just dodge the falling pianos.",
    "Outcome foggy like a cryptic latte.",
    "You’ll get a yes with a side of glitter.",
    "Refused; the horizon shuddered.",
    "Luck favors you, yet the shadows grin.",
    "No chance, a raven said so.",
    "Absolutely yes, in echoing stereo.",
    "Denied, the moon rolled its eyes.",
    "Approval granted by cosmic squirrels.",
    "Outcome bleak, like a silent carnival.",
    "Yes, but pay the toll in riddles.",
    "No, the timeline snarled.",
    "Most likely, if you whistle bravely.",
    "Unlikely, the candles blew themselves out.",
    "Yes, though the floor may creak ominously.",
    "Nope, the prophecies scoffed.",
    "Yes, announced by dancing shadows.",
    "The spirits shrug; try again.",
    "Yes, but expect mischievous echoes.",
    "No, sealed behind a velvet curtain.",
    "Prospects bright, yet unsettlingly warm.",
    "Outcome negative; the walls whispered so.",
    "Definitely, and the wind applauds.",
    "Heck no, the clock refused time.",
    "Yes, signed in starlight ink.",
    "No, the labyrinth shifted away.",
    "Yes, but only on alternate Tuesdays.",
    "Doomed to fail, according to dust motes.",
    "Yes, though the ravens giggle.",
    "No chance; the oracle unplugged.",
    "Yes, accompanied by a polite poltergeist.",
    "No, even the shadows declined.",
    "Outcome sparkling, but faintly rattling.",
    "Nope, the tea leaves staged a protest.",
    "Yes, heralded by neon wolves.",
    "Doubtful; the thunder muttered curses.",
    "Yes, but guard your shoelaces.",
    "No; the abyss laughed softly.",
    "Yes, though the mirrors may crack.",
    "Absolutely not, the air chilled.",
    "Yes, etched in luminous graffiti.",
    "Nope, the echo swallowed it.",
    "Yes, crowned with midnight confetti.",
    "Outlook grim, like a cracked music box.",
    "Yes, but expect suspicious giggles.",
    "No, the lanterns flickered out.",
    "Yes, with eerie bells chiming.",
    "No, the shadows shook their heads.",
    "Yes, but the floor might vanish.",
    "No, the constellation vetoed you.",
    "Yes, celebrated by spectral kittens.",
    "Nope, the fog signed a petition.",
    "Yes, with unsettling enthusiasm.",
    "No, the attic creaked disapproval.",
    "Yes, and the night applauds.",
    "No chance; even your sock rejected it.",
    "Yes, but a ghost wants snacks.",
    "No, the prophecy fell asleep.",
    "Yes, accompanied by distant whispers.",
    "No, the candles sigh heavily.",
    "Yes, spelled out in quiet thunder.",
    "No, the corridors groaned.",
    "Yes, but only under starlit drizzle.",
    "No, the wind shredded the memo.",
    "Yes, glowing like mischievous eyes.",
    "No, the clockwork heart stalled.",
    "Yes, but beware the grinning shadows.",
    "No, the owls filed an objection.",
    "Yes, celebrated with spectral fireworks.",
    "No, the night market closed early.",
    "Yes, but something is watching.",
    "No, the ancient coin flipped away.",
    "Yes, while the floor hums softly.",
    "Nope, the void changed the locks.",
    "Yes, the stars high-fived.",
    "No, the dusty grimoire refused.",
    "Yes, announced by invisible trumpets.",
    "No, the mirror refused eye contact.",
    "Yes, if you dare to knock thrice.",
    "No, the dreamcatcher tangled up.",
    "Yes, but the silence grins."
];

module.exports = {
    name: "8ball",
    description: "Ask the magic 8-ball a question.",
    async execute(message, args) {
        const question = args.join(" ").trim();
        if (!question) {
            return message.reply("You need to ask a question first.");
        }

        const response = responses[Math.floor(Math.random() * responses.length)];
        return message.reply(response);
    }
};